const express = require("express");

const healthRoutes = require("./health.routes");
const userAuthRoutes = require("./userRoutes/authRoutes");
const userProfileRoutes = require("./userRoutes/profileRoutes");
const userVenueBookingRoutes = require("./userRoutes/venueBookingRoutes");
const userTransactionRoutes = require("./userRoutes/transactionRoutes");
const userWishlistRoutes = require("./userRoutes/wishlistRoutes");
const userProductRatingRoutes = require("./userRoutes/productRatingRoutes");
const userVenueRatingRoutes = require("./userRoutes/venueRatingRoutes");
const userDeliveryBoyRatingRoutes = require("./userRoutes/deliveryBoyRatingRoutes");
const userProductVideoFeedLikeRoutes = require("./userRoutes/productVideoFeedLikeRoutes");
const userCartRoutes = require("./userRoutes/cartRoutes");
const userShippingAddressRoutes = require("./userRoutes/shippingAddressRoutes");
const userCheckoutRoutes = require("./userRoutes/checkoutRoutes");
const userEcomOrderRoutes = require("./userRoutes/ecomOrderRoutes");
const userNotificationRoutes = require("./userRoutes/notificationRoutes");
const userCategoryRoutes = require("./userRoutes/categoryRoutes");
const userLocationRoutes = require("./userRoutes/locationRoutes");
const userNearbyVendorRoutes = require("./userRoutes/nearbyVendorRoutes");
const vendorAuthRoutes = require("./vendorRoutes/authRoutes");
const vendorCatalogRoutes = require("./vendorRoutes/catalogRoutes");
const vendorAttributeRoutes = require("./vendorRoutes/attributeRoutes");
const vendorProductRoutes = require("./vendorRoutes/productRoutes");
const vendorProductVideoFeedRoutes = require("./vendorRoutes/productVideoFeedRoutes");
const vendorOrderRoutes = require("./vendorRoutes/orderRoutes");
const vendorWalletRoutes = require("./vendorRoutes/walletRoutes");
const vendorNotificationRoutes = require("./vendorRoutes/notificationRoutes");
const vendorProfileRoutes = require("./vendorRoutes/profileRoutes");
const vendorPlanRoutes = require("./vendorRoutes/planRoutes");
const vendorPromotionRoutes = require("./vendorRoutes/promotionRoutes");
const userPromotionRoutes = require("./userRoutes/promotionRoutes");
const vendorPanelAuthRoutes = require("./vendorPanelRoutes/authRoutes");
const venueVendorAuthRoutes = require("./venueVendorRoutes/authRoutes");
const venueVendorVenuesRoutes = require("./venueVendorRoutes/venuesRoutes");
const venueVendorBookingsRoutes = require("./venueVendorRoutes/bookingsRoutes");
const venueVendorCatalogRoutes = require("./venueVendorRoutes/catalogRoutes");
const venueVendorPlanRoutes = require("./venueVendorRoutes/planRoutes");
const venueVendorPromotionRoutes = require("./venueVendorRoutes/promotionRoutes");
const venueVendorAnnouncementRoutes = require("./venueVendorRoutes/announcementRoutes");
const venueVendorNotificationRoutes = require("./venueVendorRoutes/notificationRoutes");
const venueVendorVideoFeedRoutes = require("./venueVendorRoutes/videoFeedRoutes");
const adminAuthRoutes = require("./adminRoutes/authRoutes");
const adminUsersRoutes = require("./adminRoutes/usersRoutes");
const adminVendorsRoutes = require("./adminRoutes/vendorsRoutes");
const adminVenueVendorsRoutes = require("./adminRoutes/venueVendorsRoutes");
const adminDeliveryBoysRoutes = require("./adminRoutes/deliveryBoysRoutes");
const adminMiscRoutes = require("./adminRoutes/miscRoutes");
const adminCategoriesRoutes = require("./adminRoutes/categoriesRoutes");
const adminSubCategoriesRoutes = require("./adminRoutes/subCategoriesRoutes");
const adminChildCategoriesRoutes = require("./adminRoutes/childCategoriesRoutes");
const adminAttributesRoutes = require("./adminRoutes/attributesRoutes");
const adminBannersRoutes = require("./adminRoutes/bannersRoutes");
const adminVideoFeedRoutes = require("./adminRoutes/videoFeedRoutes");
const adminVendorPlansRoutes = require("./adminRoutes/vendorPlansRoutes");
const adminPromotionPlansRoutes = require("./adminRoutes/promotionPlansRoutes");
const adminPromotionRequestsRoutes = require("./adminRoutes/promotionRequestsRoutes");
const adminPromotionsRoutes = require("./adminRoutes/promotionsRoutes");
const promotionRequestController = require("../controllers/adminControllers/promotionRequestController");
const { protectAdmin } = require("../middleware/auth");
const adminNotificationsRoutes = require("./adminRoutes/notificationsRoutes");
const adminInboxNotificationsRoutes = require("./adminRoutes/inboxNotificationsRoutes");
const deliveryBoyAuthRoutes = require("./deliveryBoyRoutes/authRoutes");
const deliveryBoyProfileRoutes = require("./deliveryBoyRoutes/profileRoutes");
const deliveryBoyDocumentsRoutes = require("./deliveryBoyRoutes/documentsRoutes");
const deliveryBoyWalletRoutes = require("./deliveryBoyRoutes/walletRoutes");
const deliveryBoyOrderRoutes = require("./deliveryBoyRoutes/orderRoutes");
const deliveryBoyDashboardRoutes = require("./deliveryBoyRoutes/dashboardRoutes");
const deliveryBoyNotificationRoutes = require("./deliveryBoyRoutes/notificationRoutes");
const adminDeliveryWithdrawalRoutes = require("./adminRoutes/deliveryWithdrawalRoutes");
const adminDriverCodRoutes = require("./adminRoutes/driverCodRoutes");
const adminVendorWithdrawalRoutes = require("./adminRoutes/vendorWithdrawalRoutes");
const adminFaqRoutes = require("./adminRoutes/faqRoutes");
const adminStatesRoutes = require("./adminRoutes/statesRoutes");
const adminCitiesRoutes = require("./adminRoutes/citiesRoutes");
const adminSubDistrictsRoutes = require("./adminRoutes/subDistrictsRoutes");
const adminProductRoutes = require("./adminRoutes/productRoutes");
const adminVenuesRoutes = require("./adminRoutes/venuesRoutes");
const adminAmenitiesRoutes = require("./adminRoutes/amenitiesRoutes");
const adminRechargeRoutes = require("./adminRoutes/rechargeRoutes");
const adminEcomOrderRoutes = require("./adminRoutes/ecomOrderRoutes");
const adminEcomTransactionRoutes = require("./adminRoutes/ecomTransactionRoutes");
const adminVenueOrderRoutes = require("./adminRoutes/venueOrderRoutes");
const adminVenueTransactionRoutes = require("./adminRoutes/venueTransactionRoutes");
const adminRevenueRoutes = require("./adminRoutes/revenueRoutes");
const adminDashboardRoutes = require("./adminRoutes/dashboardRoutes");
const publicRoutes = require("./publicRoutes");
const mobileAppSettingsRoutes = require("./mobileAppSettingsRoutes");

const router = express.Router();

router.use("/health", healthRoutes);
router.use("/public", publicRoutes);
router.use("/user/auth", userAuthRoutes);
router.use("/user", userProfileRoutes);
router.use("/user", userCategoryRoutes);
router.use("/user", userLocationRoutes);
router.use("/user", userNearbyVendorRoutes);
router.use("/user", userVenueBookingRoutes);
router.use("/user", userTransactionRoutes);
router.use("/user", userWishlistRoutes);
router.use("/user", userProductRatingRoutes);
router.use("/user", userVenueRatingRoutes);
router.use("/user", userDeliveryBoyRatingRoutes);
router.use("/user", userProductVideoFeedLikeRoutes);
router.use("/user", userCartRoutes);
router.use("/user", userShippingAddressRoutes);
router.use("/user", userCheckoutRoutes);
router.use("/user", userEcomOrderRoutes);
router.use("/user", userNotificationRoutes);
router.use("/user", userPromotionRoutes);
router.use("/user", mobileAppSettingsRoutes);
router.use("/vendor-panel/auth", vendorPanelAuthRoutes);
router.use("/vendor/auth", vendorAuthRoutes);
router.use("/vendor", vendorCatalogRoutes);
router.use("/vendor", vendorAttributeRoutes);
router.use("/vendor", vendorProductRoutes);
router.use("/vendor", vendorProductVideoFeedRoutes);
router.use("/vendor", vendorOrderRoutes);
router.use("/vendor/wallet", vendorWalletRoutes);
router.use("/vendor", vendorNotificationRoutes);
router.use("/vendor/profile", vendorProfileRoutes);
router.use("/vendor", vendorPlanRoutes);
router.use("/vendor", vendorPromotionRoutes);
router.use("/vendor", mobileAppSettingsRoutes);
router.use("/venue-vendor/auth", venueVendorAuthRoutes);
router.use("/venue-vendor/catalog", venueVendorCatalogRoutes);
router.use("/venue-vendor/venues", venueVendorVenuesRoutes);
router.use("/venue-vendor/bookings", venueVendorBookingsRoutes);
router.use("/venue-vendor", venueVendorPlanRoutes);
router.use("/venue-vendor", venueVendorPromotionRoutes);
router.use("/venue-vendor", venueVendorAnnouncementRoutes);
router.use("/venue-vendor", venueVendorNotificationRoutes);
router.use("/venue-vendor", venueVendorVideoFeedRoutes);
router.use("/venue-vendor", mobileAppSettingsRoutes);
router.use("/admin/auth", adminAuthRoutes);
router.use("/admin/users", adminUsersRoutes);
router.use("/admin/vendors", adminVendorsRoutes);
router.use("/admin/venue-vendors", adminVenueVendorsRoutes);
router.use("/admin/delivery-boys", adminDeliveryBoysRoutes);
router.use("/admin/delivery-withdrawals", adminDeliveryWithdrawalRoutes);
router.use("/admin/delivery-cod", adminDriverCodRoutes);
router.use("/admin/vendor-withdrawals", adminVendorWithdrawalRoutes);
router.use("/admin/misc", adminMiscRoutes);
router.use("/admin/categories", adminCategoriesRoutes);
router.use("/admin/sub-categories", adminSubCategoriesRoutes);
router.use("/admin/child-categories", adminChildCategoriesRoutes);
router.use("/admin/attributes", adminAttributesRoutes);
router.use("/admin/banners", adminBannersRoutes);
router.use("/admin/video-feeds", adminVideoFeedRoutes);
router.use("/admin/plans", adminVendorPlansRoutes);
router.use("/admin/promotion-plans", adminPromotionPlansRoutes);
router.use("/admin/promotion-requests", adminPromotionRequestsRoutes);
router.get(
  "/admin/promotion-dashboard",
  protectAdmin,
  promotionRequestController.getDashboard
);
router.use("/admin/promotions", adminPromotionsRoutes);
router.use("/admin/inbox-notifications", adminInboxNotificationsRoutes);
router.use("/admin/notifications", adminNotificationsRoutes);
router.use("/delivery/auth", deliveryBoyAuthRoutes);
router.use("/delivery/profile", deliveryBoyProfileRoutes);
router.use("/delivery/documents", deliveryBoyDocumentsRoutes);
router.use("/delivery/wallet", deliveryBoyWalletRoutes);
router.use("/delivery/orders", deliveryBoyOrderRoutes);
router.use("/delivery", deliveryBoyDashboardRoutes);
router.use("/delivery", deliveryBoyNotificationRoutes);
router.use("/delivery", mobileAppSettingsRoutes);
router.use("/admin/faq", adminFaqRoutes);
router.use("/admin/states", adminStatesRoutes);
router.use("/admin/cities", adminCitiesRoutes);
router.use("/admin/sub-districts", adminSubDistrictsRoutes);
router.use("/admin/products", adminProductRoutes);
router.use("/admin/venues", adminVenuesRoutes);
router.use("/admin/amenities", adminAmenitiesRoutes);
router.use("/admin/recharges", adminRechargeRoutes);
router.use("/admin/ecom/orders", adminEcomOrderRoutes);
router.use("/admin/ecom/transactions", adminEcomTransactionRoutes);
router.use("/admin/venue/orders", adminVenueOrderRoutes);
router.use("/admin/venue/transactions", adminVenueTransactionRoutes);
router.use("/admin/payments", adminRevenueRoutes);
router.use("/admin/dashboard", adminDashboardRoutes);
module.exports = router;
