import credits from "@/data/photoCredits.json";

export type PhotoCredit = (typeof credits)[number];
export type PhotoKey =
  | "wedding-stage"
  | "banquet-hall"
  | "catering"
  | "dj"
  | "tent"
  | "table-decor"
  | "thali"
  | "spices"
  | "grocery"
  | "saree-portrait"
  | "clothing-rack"
  | "electronics"
  | "living-room"
  | "ceramics"
  | "gifts"
  | "fitness"
  | "tee"
  | "bananas"
  | "lehenga-store"
  | "brass-shop"
  | "block-print-artisan"
  | "silk-weaving"
  | "flower-seller"
  | "bhangra"
  | "baraat-horse"
  | "wedding-lights";

export const photoCredits = credits as PhotoCredit[];

const photoIndex = new Map(photoCredits.map((c) => [c.name, c]));

export function photoMeta(key: PhotoKey) {
  const c = photoIndex.get(key);
  return { width: c?.width ?? 1280, height: c?.height ?? 854 };
}

export function photoSrc(key: PhotoKey, size: 640 | 1280 = 1280) {
  return `/media/photos/${key}-${size}.webp`;
}

export function photoSrcSet(key: PhotoKey) {
  return `${photoSrc(key, 640)} 640w, ${photoSrc(key, 1280)} 1280w`;
}

/** Transparent studio cutouts generated by scripts/media/build-media.mjs. */
export const cutouts = {
  headphones: { w: 832, h: 1000, sm: 433 },
  saree: { w: 1000, h: 797, sm: 520 },
  perfume: { w: 650, h: 1000, sm: 338 },
  watch: { w: 687, h: 1000, sm: 357 },
  "brass-lantern": { w: 364, h: 1000, sm: 189 },
  sneaker: { w: 1000, h: 568, sm: 520 },
  gift: { w: 1000, h: 899, sm: 520 },
} as const;

export type CutoutKey = keyof typeof cutouts;

export function cutoutSrc(key: CutoutKey, small = false) {
  return `/media/products/${key}${small ? "-sm" : ""}.webp`;
}

export function cutoutSrcSet(key: CutoutKey) {
  const c = cutouts[key];
  return `${cutoutSrc(key, true)} ${c.sm}w, ${cutoutSrc(key)} ${c.w}w`;
}

/** Seed data ships generic SVG/PNG placeholders; treat them as "no image". */
const PLACEHOLDER = /\/uploads\/seed\/|\/uploads\/venue-categories\/|default-image|placeholder|\.svg(\?|$)/i;

export function isPlaceholder(url?: string | null) {
  return !url || PLACEHOLDER.test(url);
}

/*
 * Art direction: every photo and cutout has exactly one home on the page.
 *   hero          headphones, watch, sneaker (cutouts)
 *   categories    electronics, living-room + ceramics, perfume (cutout), spices, fitness, saree-portrait + clothing-rack
 *   products      tee, grocery, bananas (representative images for the three live products)
 *   people        block-print-artisan, silk-weaving, lehenga-store, brass-shop, flower-seller
 *   events        wedding-stage, service photos, thali, table-decor, banquet-hall
 *   promotions    saree (cutout)
 *   brand story   gifts (split into fragments)
 *   final CTA     brass-lantern, gift (cutouts)
 */

export type CategoryArt = {
  key: string;
  photo?: PhotoKey;
  cutout?: CutoutKey;
  /** Second, overlapping image layer. */
  detail?: PhotoKey;
  /** Panel colour behind cutouts and while images load. */
  tint: string;
};

const CATEGORY_ART: { match: RegExp; art: CategoryArt }[] = [
  { match: /electronic|gadget|mobile/i, art: { key: "electronics", photo: "electronics", tint: "#1d2326" } },
  { match: /home|kitchen|decor|furniture/i, art: { key: "home", photo: "living-room", detail: "ceramics", tint: "#8a6a4a" } },
  { match: /beauty|personal|cosmetic/i, art: { key: "beauty", cutout: "perfume", tint: "#e8c7b2" } },
  { match: /grocer|food|kirana/i, art: { key: "groceries", photo: "spices", tint: "#5a3112" } },
  { match: /sport|fitness|outdoor/i, art: { key: "sports", photo: "fitness", tint: "#22252a" } },
  { match: /fashion|cloth|apparel|wear/i, art: { key: "fashion", photo: "saree-portrait", detail: "clothing-rack", tint: "#7a2a1a" } },
];

const DEFAULT_CATEGORY: CategoryArt = { key: "default", tint: "#6b625a" };

export function categoryArt(name: string): CategoryArt {
  return CATEGORY_ART.find((c) => c.match.test(name))?.art ?? DEFAULT_CATEGORY;
}

/** Presentation order: electronics first (it picks up the hero's headphones), fashion last (it hands over to the product gallery). */
export function sortCategories<T extends { name: string }>(list: T[]): T[] {
  const rank = (name: string) => {
    const i = CATEGORY_ART.findIndex((c) => c.match.test(name));
    return i === -1 ? CATEGORY_ART.length : i;
  };
  return [...list].sort((a, b) => rank(a.name) - rank(b.name));
}

const SERVICE_ART: { match: RegExp; art: CategoryArt }[] = [
  { match: /baggi|buggy|horse|baraat/i, art: { key: "baggi", photo: "baraat-horse", tint: "#2b1410" } },
  { match: /bhangra|dhol|dance/i, art: { key: "bhangra", photo: "bhangra", tint: "#1f1a0a" } },
  { match: /cater/i, art: { key: "catering", photo: "catering", detail: "thali", tint: "#3a1a0e" } },
  { match: /\bdj\b|music|sound/i, art: { key: "dj", photo: "dj", tint: "#120f1f" } },
  { match: /light|decor/i, art: { key: "light", photo: "wedding-lights", detail: "table-decor", tint: "#2a1608" } },
  { match: /tent|mandap/i, art: { key: "tent", photo: "tent", tint: "#241a14" } },
];

const DEFAULT_SERVICE: CategoryArt = { key: "default", tint: "#2a0f0b" };

export function serviceArt(name: string): CategoryArt {
  return SERVICE_ART.find((c) => c.match.test(name))?.art ?? DEFAULT_SERVICE;
}

const PRODUCT_ART: { match: RegExp; photo: PhotoKey }[] = [
  { match: /t-?shirt|\btee\b/i, photo: "tee" },
  { match: /chips|snack|namkeen/i, photo: "grocery" },
  { match: /banana/i, photo: "bananas" },
];

/** Representative art for a live product whose API image is a placeholder; `undefined` renders a typographic tile. */
export function productArt(name: string): PhotoKey | undefined {
  return PRODUCT_ART.find((p) => p.match.test(name))?.photo;
}
